### ISSUE TITLE
Use ANTLR to generate grammar 

### ISSUE THREAD

**Issue by jasonrbr** [jasonrbr/CodeReader#15]
This stems from being able to "walk" the tree than antlr creates.
- [x] Use antlr to create parser, lever, etc
- [ ] parse c++ code via grammar library instead of regex 
- [ ] ability to detect multiple statement in one line 
- [ ] ability to detect one statement spanning many lines
- [ ] detect comments right above functions
- [ ] Detect global variables, libraries included, etc
- [ ] Discuss support for templates, namespaces, etc

**Comment by alexandrabrown** [comment]
Updated with antlr points
