### ISSUE TITLE
Printing functions line by line - use the menu to do this

### ISSUE THREAD

**Issue by jasonrbr** [jasonrbr/CodeReader#8]
- [ ] Grab function line by line and plop it in the panel. Then you can use the arrow keys and "say" will read the function to you 💃

**Comment by alexandrabrown** [comment]
Discuss if we want this functionality: Maybe it just reads code.

**Comment by thebenismightier** [comment]
"Read Function" in submenu will grab the implementation even if the declaration is separate from the definite
